INSERT INTO products 
    (id, product_name, product_description, category, price, image_url) 
VALUES
    ("1", "iphone 16", "Latest apple iphone", "mobile", 75000, "uploads/images/products/iphone-16.jpg"),
	("2", "macbook pro", "Latest apple macbook pro", "electronics", 150000, "uploads/images/products/macbookpro.jpg"),
    ("3", "samsung galaxy s21", "Latest samsung galaxy s21", "mobile", 65000, "uploads/images/products/samsung-galaxy-s21.jpg"),
    ("4", "oneplus 9", "Latest oneplus 9", "mobile", 55000, "uploads/images/products/oneplus-9.jpg"),
    ("5", "sony bravia 55 inch", "Latest sony bravia 55 inch", "tv", 75000, "uploads/images/products/sony-bravia-55-inch.jpg"),
    ("6", "lg 55 inch", "Latest lg 55 inch", "tv", 65000, "uploads/images/products/lg-55-inch.jpg"),
    ("7", "samsung 55 inch", "Latest samsung 55 inch", "tv", 75000, "uploads/images/products/samsung-55-inch.jpg"),
    ("8", "mi 55 inch", "Latest mi 55 inch", "tv", 45000, "uploads/images/products/mi-55-inch.jpg"),
    ("9", "oneplus buds", "Latest oneplus buds", "earphone", 5000, "uploads/images/products/oneplus-buds.jpg"),
    ("10", "apple airpods", "Latest apple airpods", "earphone", 15000, "uploads/images/products/apple-airpods.jpg"),
    ("11", "samsung buds", "Latest samsung buds", "earphone", 8000, "uploads/images/products/samsung-buds.jpg"),
    ("12", "mi buds", "Latest mi buds", "earphone", 3000, "uploads/images/products/mi-buds.jpg"),
    ("13", "oneplus watch", "Latest oneplus watch", "watch", 15000, "uploads/images/products/oneplus-watch.jpg"),
    ("14", "apple watch", "Latest apple watch", "watch", 25000, "uploads/images/products/apple-watch.jpg"),
    ("15", "samsung watch", "Latest samsung watch", "watch", 20000, "uploads/images/products/samsung-watch.jpg"),
    ("16", "mi watch", "Latest mi watch", "watch", 10000, "uploads/images/products/mi-watch.jpg"),
    ("17", "oneplus tv", "Latest oneplus tv", "tv", 75000, "uploads/images/products/oneplus-tv.jpg"),
    ("18", "tomato", "Fresh tomato", "vegetable", 50, "uploads/images/products/tomato.jpg"),
    ("19", "potato", "Fresh potato", "vegetable", 30, "uploads/images/products/potato.jpg"),
    ("20", "onion", "Fresh onion", "vegetable", 40, "uploads/images/products/onion.jpg"),
    ("21", "apple", "Fresh apple", "fruits", 100, "uploads/images/products/apple.jpg"),
    ("22", "banana", "Fresh banana", "fruits", 40, "uploads/images/products/banana.jpg"),
    ("23", "orange", "Fresh orange", "fruits", 60, "uploads/images/products/orange.jpg"),
    ("24", "mango", "Fresh mango", "fruits", 80, "uploads/images/products/mango.jpg"),
    ("25", "grapes", "Fresh grapes", "fruits", 100, "uploads/images/products/grapes.jpg"),
    ("26", "strawberry", "Fresh strawberry", "fruits", 150, "uploads/images/products/strawberry.jpg"),
    ("27", "blueberry", "Fresh blueberry", "fruits", 200, "uploads/images/products/blueberry.jpg"),
    ("28", "blackberry", "Fresh blackberry", "fruits", 250, "uploads/images/products/blackberry.jpg"),
    ("29", "raspberry", "Fresh raspberry", "fruits", 300, "uploads/images/products/raspberry.jpg"),
    ("30", "kiwi", "Fresh kiwi", "fruits", 50, "uploads/images/products/kiwi.jpg"),
    ("31", "pineapple", "Fresh pineapple", "fruits", 100, "uploads/images/products/pineapple.jpg"),
    ("32", "watermelon", "Fresh watermelon", "fruits", 50, "uploads/images/products/watermelon.jpg"),
    ("33", "pomegranate", "Fresh pomegranate", "fruits", 80, "uploads/images/products/pomegranate.jpg"),
    ("34", "guava", "Fresh guava", "fruits", 40, "uploads/images/products/guava.jpg"),
    ("35", "papaya", "Fresh papaya", "fruits", 60, "uploads/images/products/papaya.jpg");


INSERT INTO inventory 
    (product_id, quantity)
VALUES
    ("1", 10),
    ("2", 5),
    ("3", 15),
    ("4", 20),
    ("5", 10),
    ("6", 5),
    ("7", 15),
    ("8", 20),
    ("9", 10),
    ("10", 5),
    ("11", 15),
    ("12", 20),
    ("13", 10),
    ("14", 5),
    ("15", 15),
    ("16", 20),
    ("17", 10),
    ("18", 100),
    ("19", 200),
    ("20", 150),
    ("21", 100),
    ("22", 200),
    ("23", 150),
    ("24", 100),
    ("25", 200),
    ("26", 150),
    ("27", 100),
    ("28", 200),
    ("29", 150),
    ("30", 100),
    ("31", 200),
    ("32", 150),
    ("33", 100),
    ("34", 200),
    ("35", 150);